### PR TITLE
dependencies: use containernetworking/plugins v0.9.1

### PR DESCRIPTION
**Pull request by maiqueb**
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

**What this PR does / why we need it**:
This PR updates the containernetworking plugins to v0.9.1, which provide safer netns manipulation abstractions.

**Special notes for your reviewer**:
None

```release-note
Update the golang package github.com/containernetworking/plugins v0.9.1. 

As a side effect, the following packages are also updated:
  - vishvananda/netlink
  - containernetworking/cni
  - onsi/gomega
  - vishvananda/netns
  - golang/net
```

### CODE REVIEW

**Comment by maiqueb** [comment]
/approve cancel

Auto-approve sucks.

**Comment by maiqueb** [comment]
@phoracek do I have your blessing on this one ?

**Comment by phoracek** [comment]
/lgtm

Always!

**Pull request merged**
