### PR TITLE
Release v0.5.0

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

This release delivers integration with priority classes. That should make it safer to run mixed environments with control-plane and user workload sharing resources of the same node.

**Special notes for your reviewer**:

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by phoracek** [comment]
/hold

Should not be approved

**Comment by oshoval** [comment]
The bot trust me xD

**Comment by maiqueb** [comment]
> /hold
> 
> Should not be approved (bad bot!)

Yeah, the bot treats anything sent by a repo admin as pre-approved. It sucks.

You''ll have to fill the release note for this. Now that I think about it, @oshoval 's patch should have had one. Bad maintainers 0_o

**Comment by oshoval** [comment]
should i add to the merged PR ?

**Comment by maiqueb** [comment]
> should i add to the merged PR ?

Not sure, seems @phoracek already wrote something in this PR. I don't think it matters now. For next time, we just need to pay better attention.

**Comment by phoracek** [comment]
Yeah, I added mentions of the two important changes manually. To be fair, I don't recall whether we set up this repo to read release notes from the prepared template...

@maiqueb are you ok with this getting merged?

**Comment by maiqueb** [comment]
> Yeah, I added mentions of the two important changes manually. To be fair, I don't recall whether we set up this repo to read release notes from the prepared template...

It does all that. We just got to remember to use it.

> 
> @maiqueb are you ok with this getting merged?
Sure.

/approve
/hold cancel

**Comment by maiqueb** [comment]
/lgtm

You''ll have to fill the release note for this.

**Comment by phoracek** [comment]
Thanks

**Pull request merged**
