### PR TITLE
Fix issues preventing image generation

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
Two issues were found that prevented image generation:
  - The publish script was not executable.
  - The git command to get the commit-id (for the img tag) was performed outside the git repo.

### CODE REVIEW

**Comment by phoracek** [comment]
I think that you need https://github.com/kubevirt/cluster-network-addons-operator/pull/335 to copy .git too https://github.com/kubevirt/cluster-network-addons-operator/pull/335

**Comment by maiqueb** [comment]
> I think that you need [kubevirt/cluster-network-addons-operator#335](https://github.com/kubevirt/cluster-network-addons-operator/pull/335) to copy .git too [kubevirt/cluster-network-addons-operator#335](https://github.com/kubevirt/cluster-network-addons-operator/pull/335)

I've added a commit to this PR that executes the git command in the repo instead. 

Would you prefer that approach (copy the .git to the tmp folder) ?

**Comment by phoracek** [comment]
I think it would be better. The idea is that all commands are executed under the copy in /tmp. Isolating it from whatever you have in your local repository and making sure it can be executed on "any" environment. While getting the commit in your original repo is probably harmless, I believe it would be better to keep the behaviour consistent with the "/tmp system".

Once we will start automating releasing, it will be needed anyway.

**Comment by maiqueb** [comment]
> I think it would be better. The idea is that all commands are executed under the copy in /tmp. Isolating it from whatever you have in your local repository and making sure it can be executed on "any" environment. While getting the commit in your original repo is probably harmless, I believe it would be better to keep the behaviour consistent with the "/tmp system".
> 
> Once we will start automating releasing, it will be needed anyway.

No argument against it, and if future commands will require .git, I'm sold.

Done.

**Pull request merged**
