### PR TITLE
Allow using more interface types

### PR DESCRIPTION
**Pull request by kvaps**
**What this PR does / why we need it**:

This PR adds an opportunity to use any type of linux interface.
The check is updated to exclude only interfaces with `master` attribute specified (bridged or bonded)

**Special notes for your reviewer**:

Slack thread:
https://kubernetes.slack.com/archives/C8ED7RKFE/p1650358592416439?thread_ts=1649933015.379819

**Release note**:

```release-note
Allow using any type of linux interface: vlans, vxlans, bridges are now supported
```

### CODE REVIEW

**Comment by maiqueb** [comment]
Thanks for this PR. For such a change to be merged, you'd need to add at least unit tests to https://github.com/kubevirt/macvtap-cni/blob/main/pkg/deviceplugin/plugin_test.go#L218

**Comment by maiqueb** [comment]
Please consider rebasing @kvaps .

**Comment by kenstrickler** [comment]
Hello, is this PR just waiting on a rebase? I'd love to be able to use this feature in our cluster.

**Comment by maiqueb** [comment]
> Hello, is this PR just waiting on a rebase? I'd love to be able to use this feature in our cluster.

From my perspective, it requires at least unit tests. That, plus the obvious rebase.

A couple of e2e tests would be good to have, but since we rely on whatever interfaces are available in the nodes created by kubevirtci, I'm unsure how feasible that is.

**Pull request closed without merging**
