### PR TITLE
Release v0.12.0

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
New release !

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oshoval** [comment]
Thanks
/lgtm

**Comment by oshoval** [comment]
something is weird

jobs finished and i dont see image yet 
https://quay.io/repository/kubevirt/macvtap-cni?tab=tags&tag=latest
(unless need to wait more because there are some more jobs)

kraken page exists
https://github.com/kubevirt/macvtap-cni/releases/tag/v0.12.1
but title and docker pull example doesnt match

no rush, but fyi please

thanks

**Comment by maiqueb** [comment]
everything is fine afaict; you only had to wait a little bit more. 

Anyway. I got bigger fish to fry than this. If it's broken, please open an issue which we can prioritize and track, and we'll eventually get to it.

**Comment by oshoval** [comment]
it is still not there
but no worries, @ashokpariya0 told he is on it
thanks

**Comment by ashokpariya0** [comment]
> everything is fine afaict; you only had to wait a little bit more.
> 
> Anyway. I got bigger fish to fry than this. If it's broken, please open an issue which we can prioritize and track, and we'll eventually get to it.
>
No worries, I think I’ve figured out the issue. It’s related to the `IMAGE_TAG`, which runs in a local scope when using `make release`. For the multi-platform setup, I combined the full image name, and I also missed testing the `make release` part. I’ll post the fix soon.

**Comment by ashokpariya0** [comment]
> something is weird
> 
> jobs finished and i dont see tagged image yet https://quay.io/repository/kubevirt/macvtap-cni?tab=tags&tag=latest
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/release-macvtap-cni/1867210285081694208 https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-macvtap-cni/1867210285006196736
> 
> (unless need to wait more because there are some more jobs)
> 
> kraken page exists https://github.com/kubevirt/macvtap-cni/releases/tag/v0.12.1 but title and docker pull example doesnt match (both doesnt exist)
> 
> no rush, but fyi please
> 
> thanks
>
PR: https://github.com/kubevirt/macvtap-cni/pull/129 fixes above issue.

**Pull request merged**
